/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MagazaUsernameRouteImport } from './routes/magaza.$username'
import { Route as PanelTabRouteImport } from './routes/panel.$tab'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MagazaUsernameRoute = MagazaUsernameRouteImport.update({
  id: '/magaza/$username',
  path: '/magaza/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelTabRoute = PanelTabRouteImport.update({
  id: '/panel/$tab',
  path: '/panel/$tab',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/magaza/$username': typeof MagazaUsernameRoute
  '/panel/$tab': typeof PanelTabRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/magaza/$username': typeof MagazaUsernameRoute
  '/panel/$tab': typeof PanelTabRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/magaza/$username': typeof MagazaUsernameRoute
  '/panel/$tab': typeof PanelTabRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/magaza/$username' | '/panel/$tab'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/magaza/$username' | '/panel/$tab'
  id: '__root__' | '/' | '/magaza/$username' | '/panel/$tab'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MagazaUsernameRoute: typeof MagazaUsernameRoute
  PanelTabRoute: typeof PanelTabRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/magaza/$username': {
      id: '/magaza/$username'
      path: '/magaza/$username'
      fullPath: '/magaza/$username'
      preLoaderRoute: typeof MagazaUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel/$tab': {
      id: '/panel/$tab'
      path: '/panel/$tab'
      fullPath: '/panel/$tab'
      preLoaderRoute: typeof PanelTabRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MagazaUsernameRoute: MagazaUsernameRoute,
  PanelTabRoute: PanelTabRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
